---
title: "ECO 395 Homework 4: Taylor Neal"
output: rmarkdown::github_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(LICORS)
library(foreach)
library(arules)
library(arulesViz)
library(igraph)
library(corrplot)
library(knitr)

wine <- read.csv("https://raw.githubusercontent.com/taylorneal/homework-4/master/data/wine.csv", header = TRUE)
social_marketing <- read.csv("https://raw.githubusercontent.com/taylorneal/homework-4/master/data/social_marketing.csv", header = TRUE)
groceries <- readLines("https://raw.githubusercontent.com/taylorneal/homework-4/master/data/groceries.txt")

set.seed(12)
```
## 1) Clustering and PCA


Intro

```{r PCA-table, echo = FALSE, fig.align = 'center'}

X = wine[,(1:11)]
X = scale(X, center = TRUE, scale = TRUE)

PCA = prcomp(X, rank = 11)

kable(round(PCA$rotation[,1:5],2))

```

TBU

```{r PCA-scatter, echo = FALSE, fig.align = 'center'}

ggplot(wine) + 
  geom_point(aes(alcohol, total.sulfur.dioxide, 
                 color = PCA$x[,1]), size = 2) +
  scale_color_gradient2(low = 'red', mid = 'light grey', high = 'cyan', 
                        name = 'PC1')

```

TBU

```{r tot-sulf-diox-alc-1, echo = FALSE, fig.align = 'center'}

clust1 = kmeanspp(X, k = 3, nstart = 10)

ggplot(wine) + 
  geom_point(aes(alcohol, total.sulfur.dioxide, 
                 fill = factor(clust1$cluster), color = color), size = 2, pch = 21) + 
  scale_fill_manual(values=c("blue", "cyan", "red")) #+ facet_wrap(~quality)

```


TBU

```{r tot-sulf-diox-alc-2, echo = FALSE, fig.align = 'center'}

wine$predict_rw = 'Correct'
wine[clust1$cluster == 3 & wine$color == 'white', 'predict_rw'] = 
  'Incorrect (white)'
wine[clust1$cluster != 3 & wine$color == 'red', 'predict_rw'] = 
  'Incorrect (red)'
white_pct = 1 - sum(wine$predict_rw == 'Incorrect (white)') / 
  sum(wine$color == 'white')
red_pct = 1 - sum(wine$predict_rw == 'Incorrect (red)') / 
  sum(wine$color == 'red')

ggplot(wine) + 
  geom_point(aes(alcohol, total.sulfur.dioxide, 
                 color = factor(predict_rw)), size = 2) +
  scale_color_manual(values=c("light gray", "red", "cyan"))

```


TBU

```{r tot-sulf-diox-alc-3, echo = FALSE, fig.align = 'center'}

ggplot(wine) + 
  geom_point(aes(alcohol, total.sulfur.dioxide, 
                 fill = factor(clust1$cluster), color = color), size = 2, pch = 21) + 
  scale_fill_manual(values=c("blue", "cyan", "red")) + facet_wrap(~quality)

```

TBU

## 2) Market Segmentation

TBU 


## 3) Association Rules for Grocery Purchases


Intro

```{r rules-scatter, echo = FALSE, fig.align = 'center', results = 'hide'}

groceries = split(groceries, seq_len(length(groceries)))

for (i in seq(length(groceries))) {
  groceries[[i]] = scan(text = groceries[[i]], what = '', sep = ',', 
                        quiet = TRUE)
}

groceries = lapply(groceries, unique)

groceries = as(groceries, "transactions")

rules = apriori(groceries, parameter = list(support = 0.01, 
                                            confidence = 0.1, maxlen = 2))

plot(subset(rules, lift > 1.0001), measure = c("support", "lift"), shading = "confidence")

```


TBU

```{r rules-graph, echo = FALSE, fig.align = 'center', fig.width = 10, fig.height = 8}

sub1 = subset(rules, lift > 1.8 & confidence > 0.3)

plot(sub1, method = 'graph')

```


Conclusion